[package]
name = "magicutil"
version = "0.1.0"
authors = ["mark"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 'z'
lto = true
debug-assertions = false
debug = false
rpath = false
panic = "abort"

[dependencies]
md5 = "0.7.0"
mac_address = "1.1.1"
java-properties = { version = "1.3.0", default-features = false }
simple-error = "0.2.3"
clap = "2.33.3"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = "1.0"